service: serverless-scraper

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  exclude:
    - tests/**

functions:
  scrap:
    handler: scraper/scrap.get_title
    events:
      - http:
          path: scrap
          method: post
